### PR TITLE
Add traversel visitor VashMarkupContent

### PR DESCRIPTION
**Pull request by differui**
Add traversel visitor VashMarkupContent.

### CODE REVIEW

**Comment by kirbysayshi** [comment]
To be honest, I forgot this was here! Just curious, what are you using it for?

**Comment by differui** [comment]
Hi @kirbysayshi, I'm looking for a Razor compiler in Node.js using for rendering AST of Razor docs.

**Comment by kirbysayshi** [comment]
Whoa interesting! I think during the massive rewrite a few years ago I forgot to delete traversal. More than willing to keep it around, if it helps you. Any chance you'd like to write a test for it? I really cannot guarantee that it works properly.

**Comment by differui** [comment]
OK! I will try to do that. ;)

**Comment by kirbysayshi** [comment]
Otherwise, an option is to make a separate package! Traversal isn't really a public API, and isn't used anywhere in the code base. But if you wanted to make it a separate thing that would be cool too :)

**Comment by kirbysayshi** [comment]
Going to close due to inactivity. Reopen if progress was made!

**Pull request closed without merging**
