### PR TITLE
Add browserify instructions to the readme

### PR DESCRIPTION
**Pull request by chevett**
can i do this?

### CODE REVIEW

**Comment by kirbysayshi** [comment]
Looks great! But instead of adding it to README.md, please add it to README.vash, which generates README.md (for the table of contents generation).

**Comment by chevett** [comment]
dang, very meta.  ok, will do.

**Comment by kirbysayshi** [comment]
Yeah, sorry about that. It’s kind of a testbed for vash parsing non-html
data. But unfortunately it adds complication :(

Yip yip,
~ Drew*

**Comment by kirbysayshi** [comment]
I forgot to mention, don't worry about generating the new README.md, I can do that if it's too much trouble!

**Comment by chevett** [comment]
oh no np, I'm interested in figuring it out.  Things just got a little
crazy on my end.  I think I'll get to it today.

**Comment by kirbysayshi** [comment]
Thanks, I ended up just merging this in manually, basically.

**Comment by chevett** [comment]
Doh, I swear I was going to get around to it!  Thanks!

Thanks, I ended up just merging this in manually, basically.

—
Reply to this email directly or view it on GitHub
<https://github.com/kirbysayshi/vash/pull/51#issuecomment-123571245>.

**Pull request merged**
